spring:
  application:
    name: url-shortener

  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener
    username: rizaldydecena
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: 487035abe84b117eced66405a51a30dcc954323fa570ca2576ff0a8962c6eeb9
  expiration: 172800000

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: ERROR
    org.url.shortener: DEBUG